version: '3'
services:
  app:
    image: 'httpd:2.4.49'
    container_name: "poc_apache_vuln"
    ports:
      - '41773:80'
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      poc_apache_vuln:
        ipv4_address: 172.16.0.2

networks:
  poc_apache_vuln:
    ipam:
      config:
        - subnet: 172.16.0.0/24
